In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import LineString
import pydeck as pdk

In [2]:
%%time
df = pd.read_parquet("trajectories/ALL_GOM_tanker_2019-2021_traj.parquet")
df = pd.read_json(df.to_json())
df

CPU times: user 37.5 s, sys: 3.99 s, total: 41.5 s
Wall time: 41.4 s

,mmsi,path,ts
0,3791472,"[[-92.04048, 26.13211], [-92.04049, 26.13213],...","[140700.0, 141000.0, 141300.0, 141600.0, 14190..."
1,205042000,"[[-89.2095, 27.24959], [-89.26068, 27.33388], ...","[80076600.0, 80077800.0, 80078100.0, 80078400...."
2,205086000,"[[-93.48448, 26.39778], [-93.56166, 26.50175],...","[77814000.0, 77816700.0, 77819400.0, 77821800...."
3,205089000,"[[-90.35513, 24.80777], [-90.36815, 24.81126],...","[94534200.0, 94535100.0, 94536000.0, 94536300...."
4,205097000,"[[-93.45964, 26.5793], [-93.6274, 26.76886], [...","[82272300.0, 82275300.0, 82275600.0, 82276200...."
...,...,...,...
2972,642122021,"[[-93.82248, 25.65528], [-93.85108, 25.6612700...","[19596300.0, 19596900.0, 19597500.0, 19597800...."
2973,645337000,"[[-91.57331, 26.81737], [-91.60873, 26.85394],...","[17980500.0, 17981400.0, 17982600.0, 17982900...."
2974,710016250,"[[-88.35071, 25.61065], [-88.36058, 25.62274],...","[12231000.0, 12231300.0, 12231600.0, 12231900...."
2975,710033290,"[[-92.98647, 26.33258], [-93.03388, 26.37598],...","[76974900.0, 76976100.0, 76976400.0, 76977000...."
2976,866666666,"[[-93.64103, 29.42988], [-93.64099, 29.43002]]","[33564300.0, 33564900.0]"

In [4]:
#set of timestamps for slected MMSI
tss = sorted(list(set([x for y in df.loc[1:4].ts.tolist() for x in y if x > 0])))

In [5]:
import time

layer = pdk.Layer(
    "TripsLayer",
    df.loc[1:4],
    get_path="path",
    get_timestamps="ts",
    get_color=[253, 128, 93],
    opacity=0.8,
    width_min_pixels=5,
    rounded=True,
    trail_length=100000,
    current_time=tss[0]
)
view_state = pdk.ViewState(latitude = 29.41129858, longitude = -94.8185302, zoom=4, bearing=20, pitch=20)
# Render
r = pdk.Deck(
    map_provider="mapbox",
    map_style=pdk.map_styles.SATELLITE,
    api_keys={"mapbox": "pk.eyJ1IjoiZ3JvbDIwMjAiLCJhIjoiY2tvajI0MW5pMDMxMDJ3bzdpN3dzbHBidyJ9.jxYSuCXT1u1eFKMMWwSFVg"},
    layers=[layer],
    initial_view_state=view_state
)
r.show()

DeckGLWidget(carto_key=None, custom_libraries=[], google_maps_key=None, json_input='{"initialViewState": {"bea…

In [6]:
# Animate
for i, ct in enumerate(tss):
    layer.current_time = ct
    r.update()
    time.sleep(0.05)
    if i % 100 == 0:
        print(i, ct)

0 77814000.0
100 77853000.0
200 77896500.0
300 77943000.0
400 77985900.0
500 78023400.0
600 78069600.0
700 78099600.0
800 78132900.0
900 78165600.0
1000 78215700.0
1100 78253500.0
1200 78284100.0
1300 78314100.0
1400 78370500.0
1500 78422400.0
1600 78478800.0
1700 80099100.0
1800 80132100.0
1900 80163000.0
2000 80196300.0
2100 80228700.0
2200 80262600.0
2300 80299800.0
2400 80331900.0
2500 80398500.0
2600 80482200.0
2700 80556900.0
2800 80598000.0
2900 80654100.0
3000 80691900.0
3100 80733000.0
3200 80765700.0
3300 80798700.0
3400 80829300.0
3500 82302900.0
3600 82333500.0
3700 82364700.0
3800 82395900.0
3900 82427100.0
4000 82457100.0
4100 82487700.0
4200 82517700.0
4300 82548600.0
4400 82579200.0
4500 82609500.0
4600 82640400.0
4700 82671300.0
4800 82702200.0
4900 82732200.0
5000 82762200.0
5100 90572400.0
5200 90602400.0
5300 90636000.0
5400 90667500.0
5500 90700500.0
5600 90735300.0
5700 90768900.0
5800 90802800.0
5900 90836700.0
6000 90867900.0
6100 90902700.0
6200 90933900.0
6300 90968700.0
6400 91363500.0
6500 91396500.0
6600 91428900.0
6700 91460400.0
6800 91491000.0
6900 91523100.0
7000 91554300.0
7100 91586400.0
7200 91619400.0
7300 91657500.0
7400 91691100.0
7500 91740900.0
7600 91770900.0
7700 91800900.0
7800 91830900.0
7900 91861200.0
8000 94602000.0
8100 94635900.0
8200 94665900.0

In [ ]:
len(tss)